name: quran_twekl_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.18.0-165.1.beta <3.0.0"
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter  
  intl: ^0.17.0       
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  adhan_dart: ^1.0.8
  equatable: ^2.0.3
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  rxdart: ^0.27.7 
  adhan: ^1.1.16
  location: ^4.2.0
  scroll_loop_auto_scroll: ^0.0.5
  # background_location: ^0.8.1
  http: ^0.13.4
  sqflite_common_ffi: ^2.1.1+1
  audioplayers: ^2.0.0
  dio: ^4.0.6
  scroll_snap_list: ^0.9.1
  flutter_qiblah: ^2.1.0
  flutter_compass: ^0.7.0
  data_connection_checker: ^0.3.4
  path_provider: ^2.0.11
  bloc_test: ^9.0.3
  just_audio: ^0.9.28
  riverpod: ^1.0.3
  percent_indicator: ^4.2.2
  hooks_riverpod: ^1.0.4
  dartz: ^0.10.1
  flutter_svg: ^1.1.6
  google_maps_flutter: ^2.2.2
  connectivity_plus: ^2.3.6+1
  provider: ^6.0.3
  span_builder: ^0.1.0
  visibility_detector: ^0.3.3
  get_it: ^7.2.0
  rect_getter: ^1.1.0
  scrollable_positioned_list: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  mockito: ^5.2.0
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    - assets/audio/asr2.mpga
    - assets/audio/asr3.mpga
    - assets/database/testDB2.db
    - assets/images/quran.png
    - assets/images/favEndOfAyah-rvbg.png
    - assets/images/endOfPageIcon.png
    - assets/images/end_Surah-rvbg.png
    - assets/images/juzz_icon_rbg.png
    - assets/images/Qari_Images/abdulbast.png
    - assets/images/download.png
    - assets/images/Qari_Images/abdullah-basfar.png
    - assets/images/Qari_Images/abdurrahmaansudais.png
    - assets/images/AudioController/next-ayah-right-controller-icon.png
    - assets/images/AudioController/next-ayah-left-controller-icon.png
    - assets/images/AudioController/next-surah-left-controller-icon.png
    - assets/images/AudioController/next-surah-right-controller-icon.png
    - assets/images/AudioController/next_audio.png
    - assets/images/AudioController/back_audio.png
    - assets/images/AudioController/next.png
    - assets/images/AudioController/back.png
    - assets/images/AudioController/play_btn.png
    - assets/images/AudioController/pause.png
    - assets/images/home.png
    - assets/images/scroll.png
    - assets/images/quranReadingIcon.png
    - assets/images/readQuranNavigationIcon.png
    - assets/images/quran2.png
    - assets/images/Qari_Images/Maher_Al_Muaiqly.png
    - assets/images/Qari_Images/mohamed-ayoub.png
    - assets/images/Qari_Images/Mishary.png
    - assets/images/Qari_Images/AbuBakr_Ash-Shaatree.png
    - assets/images/Qari_Images/Ibrahim_Akhdar.png
    - assets/images/compass.svg
    - assets/images/needle.svg
    - assets/images/mosque.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ISLAMIC
      fonts:
        - asset: assets/fonts/Al Majeed Quranic Font_shiped.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: MUHAMMADI
      fonts:
        - asset: assets/fonts/MUHAMMADI QURANIC FONT.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
      
    - family: "NOORHIDAYAT"
      fonts:
        - asset: assets/fonts/noorehidayat.ttf
          weight: 700

    - family: "MEQURAN"
      fonts:
        - asset: assets/fonts/me_quran_volt_newmet.ttf
          weight: 700

    - family: "ROBOTO"
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf 
        - asset: assets/fonts/roboto/Roboto-Bold.ttf 
        
          weight: 700

    - family: "NOTOSANSARABIC"
      fonts:
        - asset: assets/fonts/NotoSansArabic-VariableFont_wdth,wght.ttf
          weight: 700

    - family: "ALMARAI"
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 700

    - family: "TAJAWAL"
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 700      
          #NotoSansArabic-VariableFont_wdth,wght.ttf

  #Roboto-Regular.ttf    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
