const Map<int, dynamic> mapPageToSurah = {
  1: {"english": "Al-Faatiha", "arabic": "ٱلْفَاتِحَةِ", "number": 1},
  2: {"english": "Al-Baqara", "arabic": "البَقَرَةِ", "number": 2},
  50: {"english": "Aal-i-Imraan", "arabic": "آلِ عِمۡرَانَ", "number": 3},
  77: {"english": "An-Nisaa", "arabic": "النِّسَاءِ", "number": 4},
  106: {"english": "Al-Maaida", "arabic": "المَائـِدَةِ", "number": 5},
  128: {"english": "Al-An'aam", "arabic": "الأَنۡعَامِ", "number": 6},
  151: {"english": "Al-A'raaf", "arabic": "الأَعۡرَافِ", "number": 7},
  177: {"english": "Al-Anfaal", "arabic": "الأَنفَالِ", "number": 8},
  187: {"english": "At-Tawba", "arabic": "التَّوۡبَةِ", "number": 9},
  208: {"english": "Yunus", "arabic": "يُونُسَ", "number": 10},
  221: {"english": "Hud", "arabic": "هُودٍ", "number": 11},
  235: {"english": "Yusuf", "arabic": "يُوسُفَ", "number": 12},
  249: {"english": "Ar-Ra'd", "arabic": "الرَّعۡدِ", "number": 13},
  255: {"english": "Ibrahim", "arabic": "إِبۡرَاهِيمَ", "number": 14},
  262: {"english": "Al-Hijr", "arabic": "الحِجۡرِ", "number": 15},
  267: {"english": "An-Nahl", "arabic": "النَّحۡلِ", "number": 16},
  282: {"english": "Al-Israa", "arabic": "الإِسۡرَاءِ", "number": 17},
  293: {"english": "Al-Kahf", "arabic": "الكَهۡفِ", "number": 18},
  305: {"english": "Maryam", "arabic": "مَرۡيَمَ", "number": 19},
  312: {"english": "Taa-Haa", "arabic": "طه", "number": 20},
  322: {"english": "Al-Anbiyaa", "arabic": "الأَنبِيَاءِ", "number": 21},
  332: {"english": "Al-Hajj", "arabic": "الحَجِّ", "number": 22},
  342: {"english": "Al-Muminoon", "arabic": "المُؤۡمِنُونَ", "number": 23},
  350: {"english": "An-Noor", "arabic": "النُّورِ", "number": 24},
  359: {"english": "Al-Furqaan", "arabic": "الفُرۡقَانِ", "number": 25},
  367: {"english": "Ash-Shu'araa", "arabic": "الشُّعَرَاءِ", "number": 26},
  377: {"english": "An-Naml", "arabic": "النَّمۡلِ", "number": 27},
  385: {"english": "Al-Qasas", "arabic": "القَصَصِ", "number": 28},
  396: {"english": "Al-Ankaboot", "arabic": "العَنكَبُوتِ", "number": 29},
  404: {"english": "Ar-Room", "arabic": "الرُّومِ", "number": 30},
  411: {"english": "Luqman", "arabic": "لُقۡمَانَ", "number": 31},
  415: {"english": "As-Sajda", "arabic": "السَّجۡدَةِ", "number": 32},
  418: {"english": "Al-Ahzaab", "arabic": "الأَحۡزَابِ", "number": 33},
  428: {"english": "Saba", "arabic": "سَبَإٍ", "number": 34},
  434: {"english": "Faatir", "arabic": "فَاطِرٍ", "number": 35},
  440: {"english": "Yaseen", "arabic": "يسٓ", "number": 36},
  446: {"english": "As-Saaffaat", "arabic": "الصَّافَّاتِ", "number": 37},
  453: {"english": "Saad", "arabic": "صٓ", "number": 38},
  458: {"english": "Az-Zumar", "arabic": "الزُّمَرِ", "number": 39},
  467: {"english": "Ghafir", "arabic": "غَافِرٍ", "number": 40},
  477: {"english": "Fussilat", "arabic": "فُصِّلَتۡ", "number": 41},
  483: {"english": "Ash-Shura", "arabic": "الشُّورَىٰ", "number": 42},
  489: {"english": "Az-Zukhruf", "arabic": "الزُّخۡرُفِ", "number": 43},
  496: {"english": "Ad-Dukhaan", "arabic": "الدُّخَانِ", "number": 44},
  499: {"english": "Al-Jaathiya", "arabic": "الجَاثِيَةِ", "number": 45},
  502: {"english": "Al-Ahqaf", "arabic": "الأَحۡقَافِ", "number": 46},
  507: {"english": "Muhammad", "arabic": "مُحَمَّدٍ", "number": 47},
  511: {"english": "Al-Fath", "arabic": "الفَتۡحِ", "number": 48},
  515: {"english": "Al-Hujuraat", "arabic": "الحُجُرَاتِ", "number": 49},
  518: {"english": "Qaaf", "arabic": "قٓ", "number": 50},
  520: {"english": "Adh-Dhaariyat", "arabic": "الذَّارِيَاتِ", "number": 51},
  523: {"english": "At-Tur", "arabic": "الطُّورِ", "number": 52},
  526: {"english": "An-Najm", "arabic": "النَّجۡمِ", "number": 53},
  528: {"english": "Al-Qamar", "arabic": "القَمَرِ", "number": 54},
  531: {"english": "Ar-Rahmaan", "arabic": "الرَّحۡمَٰن", "number": 55},
  534: {"english": "Al-Waaqia", "arabic": "الوَاقِعَةِ", "number": 56},
  537: {"english": "Al-Hadid", "arabic": "الحَدِيدِ", "number": 57},
  542: {"english": "Al-Mujaadila", "arabic": "المُجَادلَةِ", "number": 58},
  545: {"english": "Al-Hashr", "arabic": "الحَشۡرِ", "number": 59},
  549: {"english": "Al-Mumtahana", "arabic": "المُمۡتَحنَةِ", "number": 60},
  551: {"english": "As-Saff", "arabic": "الصَّفِّ", "number": 61},
  553: {"english": "Al-Jumu'a", "arabic": "الجُمُعَةِ", "number": 62},
  554: {"english": "Al-Munaafiqoon", "arabic": "المُنَافِقُونَ", "number": 63},
  556: {"english": "At-Taghaabun", "arabic": "التَّغَابُنِ", "number": 64},
  558: {"english": "At-Talaaq", "arabic": "الطَّلَاقِ", "number": 65},
  560: {"english": "At-Tahrim", "arabic": "التَّحۡرِيمِ", "number": 66},
  562: {"english": "Al-Mulk", "arabic": "المُلۡكِ", "number": 67},
  564: {"english": "Al-Qalam", "arabic": "القَلَمِ", "number": 68},
  566: {"english": "Al-Haaqqa", "arabic": "الحَاقَّةِ", "number": 69},
  568: {"english": "Al-Ma'aarij", "arabic": "المَعَارِجِ", "number": 70},
  570: {"english": "Nooh", "arabic": "نُوحٍ", "number": 71},
  572: {"english": "Al-Jinn", "arabic": "الجِنِّ", "number": 72},
  574: {"english": "Al-Muzzammil", "arabic": "المُزَّمِّلِ", "number": 73},
  575: {"english": "Al-Muddaththir", "arabic": "المُدَّثِّرِ", "number": 74},
  577: {"english": "Al-Qiyaama", "arabic": "القِيَامَةِ", "number": 75},
  578: {"english": "Al-Insaan", "arabic": "الإِنسَانِ", "number": 76},
  580: {"english": "Al-Mursalaat", "arabic": "المُرۡسَلَاتِ", "number": 77},
  582: {"english": "An-Naba", "arabic": "النَّبَإِ", "number": 78},
  583: {"english": "An-Naazi'aat", "arabic": "النَّازِعَاتِ", "number": 79},
  585: {"english": "Abasa", "arabic": "عَبَسَ", "number": 80},
  586: {"english": "At-Takwir", "arabic": "التَّكۡوِيرِ", "number": 81},
  587: [
    {"english": "Al-Infitaar", "arabic": "الانفِطَارِ", "number": 82},
    {"english": "Al-Mutaffifin", "arabic": "المُطَفِّفِينَ", "number": 83}
  ],
  589: {"english": "Al-Inshiqaaq", "arabic": "الانشِقَاقِ", "number": 84},
  590: {"english": "Al-Burooj", "arabic": "البُرُوجِ", "number": 85},
  591: [
    {"english": "At-Taariq", "arabic": "الطَّارِقِ", "number": 86},
    {"english": "Al-A'laa", "arabic": "الأَعۡلَىٰ", "number": 87}
  ],
  592: {"english": "Al-Ghaashiya", "arabic": "الغَاشِيَةِ", "number": 88},
  593: {"english": "Al-Fajr", "arabic": "الفَجۡرِ", "number": 89},
  594: {"english": "Al-Balad", "arabic": "البَلَدِ", "number": 90},
  595: [
    {"english": "Ash-Shams", "arabic": "الشَّمۡسِ", "number": 91},
    {"english": "Al-Lail", "arabic": "اللَّيۡلِ", "number": 92},
  ],
  596: [
    {"english": "Ad-Dhuhaa", "arabic": "الضُّحَىٰ", "number": 93},
    {"english": "Ash-Sharh", "arabic": "الشَّرۡحِ", "number": 94},
  ],
  597: [
    {"english": "At-Tin", "arabic": "التِّينِ", "number": 95},
    {"english": "Al-Alaq", "arabic": "العَلَقِ", "number": 96},
  ],
  598: [
    {"english": "Al-Qadr", "arabic": "القَدۡرِ", "number": 97},
    {"english": "Al-Bayyina", "arabic": "البَيِّنَةِ", "number": 98},
  ],
  599: [
    {"english": "Az-Zalzala", "arabic": "الزَّلۡزَلَةِ", "number": 99},
    {"english": "Al-Aadiyaat", "arabic": "العَادِيَاتِ", "number": 100},
  ],
  600: [
    {"english": "Al-Qaari'a", "arabic": "القَارِعَةِ", "number": 101},
    {"english": "At-Takaathur", "arabic": "التَّكَاثُرِ", "number": 102},
  ],
  601: [
    {"english": "Al-Asr", "arabic": "العَصۡرِ", "number": 103},
    {"english": "Al-Humaza", "arabic": "الهُمَزَةِ", "number": 104},
    {"english": "Al-Fil", "arabic": "الفِيلِ", "number": 105},
  ],
  602: [
    {"english": "Quraish", "arabic": "قُرَيۡشٍ", "number": 106},
    {"english": "Al-Maa'un", "arabic": "المَاعُونِ", "number": 107},
    {"english": "Al-Kawthar", "arabic": "الكَوۡثَرِ", "number": 108},
  ],
  603: [
    {"english": "Al-Kaafiroon", "arabic": "الكَافِرُونَ", "number": 109},
    {"english": "An-Nasr", "arabic": "النَّصۡرِ", "number": 110},
    {"english": "Al-Masad", "arabic": "المَسَدِ", "number": 111},
  ],
  604: [
    {"english": "Al-Ikhlaas", "arabic": "الإِخۡلَاصِ", "number": 112},
    {"english": "Al-Falaq", "arabic": "الفَلَقِ", "number": 113},
    {"english": "An-Naas", "arabic": "النَّاسِ", "number": 114},
  ],
};
