// Mocks generated by Mockito 5.3.0 from annotations
// in quran_twekl_app/test/features/readQuran/UI/bloc/readQuranBloc_test.dart.
// Do not manually edit this file.

// @dart=2.9

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/get_list_ayah__page.dart'
    as _i4;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/getAllAyah.dart'
    as _i8;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/getAllSurah.dart'
    as _i2;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/getCountVersesOfSurah.dart'
    as _i6;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/getCoutVersesOfPage.dart'
    as _i5;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/getFirstNumberPageOfSurah.dart'
    as _i7;
import 'package:quran_twekl_app/Features/readQuran/domain/usecase/GetListAyahsOfSurah.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetAllSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSurah extends _i1.Mock implements _i2.GetAllSurah {
  MockGetAllSurah() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetListAyahsOfSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListAyahsOfSurah extends _i1.Mock
    implements _i3.GetListAyahsOfSurah {
  MockGetListAyahsOfSurah() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetAyahsOfPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAyahsOfPage extends _i1.Mock implements _i4.GetAyahsOfPage {
  MockGetAyahsOfPage() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetCountVersesOfPage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountVersesOfPage extends _i1.Mock
    implements _i5.GetCountVersesOfPage {
  MockGetCountVersesOfPage() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetCountVersesOfSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountVersesOfSurah extends _i1.Mock
    implements _i6.GetCountVersesOfSurah {
  MockGetCountVersesOfSurah() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetFirstNumberPageOfSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFirstNumberPageOfSurah extends _i1.Mock
    implements _i7.GetFirstNumberPageOfSurah {
  MockGetFirstNumberPageOfSurah() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GetAllAyah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllAyah extends _i1.Mock implements _i8.GetAllAyah {
  MockGetAllAyah() {
    _i1.throwOnMissingStub(this);
  }
}
